# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-3.5-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phi-3.5
  template:
    metadata:
      labels:
        app: phi-3.5
    spec:
      containers:
      - name: phi-3.5
        image: Echo9k/phi-3.5-app:latest
        ports:
        - containerPort: 80
